[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = []

[phases.build]
cmds = [
  "cd hisaab-frontend && npm install && npm run build",
  "cd backend && npm install"
]

[start]
cmd = "cd backend && node server.js"
