[build]
builder = "nixpacks"
buildCommand = "cd hisaab-frontend && npm install && npm run build && cd ../backend && npm install"

[deploy]
startCommand = "node backend/server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "hisaab"

[services.variables]
NODE_ENV = "production"
