[build]
builder = "nixpacks"
buildCommand = "cd hisaab-frontend && npm install && npm run build && cd ../backend && npm install"

[deploy]
startCommand = "node backend/server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "20"
